version: '2'

services:
  app:
    image: ellamination
    command: java -jar /app.jar
    links:
      - mongodb
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --smallfiles
